spring.application.name=brunofragadev
spring.profiles.active=local


# configuracao do JPA Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# habilitar Swagger UI
springdoc.swagger-ui.enabled=${SWAGGER_ENABLED:false}
springdoc.api-docs.enabled=${SWAGGER_ENABLED:false}

# definir o caminho do Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# Caminho da documentacao OpenAPI
springdoc.api-docs.path=/v3/api-docs

# Escanear pacotes do project
springdoc.packages-to-scan=com.brunofragadev

google.client.id=${GOOGLE_CLIENT_ID}

# JWT CONFIG
jwt.secret.key=${JWT_SECRET_KEY}
jwt.expiration.ms=3600000

#Banco de Dados PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#BREVO
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER_EMAIL}